# Generated by Django 4.2.7 on 2025-06-29 12:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_recording_days', models.IntegerField(default=30, verbose_name='Dias Máximos de Retenção')),
                ('auto_delete_enabled', models.BooleanField(default=True, verbose_name='Exclusão Automática')),
                ('storage_limit_gb', models.IntegerField(default=100, verbose_name='Limite de Armazenamento (GB)')),
                ('compression_enabled', models.BooleanField(default=True, verbose_name='Compressão Habilitada')),
                ('backup_enabled', models.BooleanField(default=False, verbose_name='Backup Habilitado')),
                ('backup_path', models.CharField(blank=True, max_length=500, verbose_name='Caminho do Backup')),
            ],
            options={
                'verbose_name': 'Configuração de Gravação',
                'verbose_name_plural': 'Configurações de Gravação',
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=500, verbose_name='Caminho do Arquivo')),
                ('file_name', models.CharField(max_length=200, verbose_name='Nome do Arquivo')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Tamanho do Arquivo (bytes)')),
                ('duration', models.IntegerField(default=0, verbose_name='Duração (segundos)')),
                ('recording_type', models.CharField(choices=[('motion', 'Detecção de Movimento'), ('manual', 'Gravação Manual'), ('scheduled', 'Gravação Programada'), ('continuous', 'Gravação Contínua')], default='motion', max_length=20, verbose_name='Tipo de Gravação')),
                ('motion_detected', models.BooleanField(default=False, verbose_name='Movimento Detectado')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Início')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Fim')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Excluído')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='cameras.camera')),
            ],
            options={
                'verbose_name': 'Gravação',
                'verbose_name_plural': 'Gravações',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MotionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Início')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Fim')),
                ('duration', models.IntegerField(default=0, verbose_name='Duração (segundos)')),
                ('confidence', models.FloatField(default=0.0, verbose_name='Confiança da Detecção')),
                ('area_affected', models.IntegerField(default=0, verbose_name='Área Afetada (pixels)')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motion_events', to='cameras.camera')),
                ('recording', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motion_events', to='recordings.recording')),
            ],
            options={
                'verbose_name': 'Evento de Movimento',
                'verbose_name_plural': 'Eventos de Movimento',
                'ordering': ['-start_time'],
            },
        ),
    ]
