# Generated by Django 4.2.7 on 2025-06-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='conversion_error',
            field=models.TextField(blank=True, null=True, verbose_name='Erro na Conversão'),
        ),
        migrations.AddField(
            model_name='recording',
            name='conversion_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('converting', 'Convertendo'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='Status da Conversão'),
        ),
        migrations.AddField(
            model_name='recording',
            name='converted_file_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Arquivo Convertido'),
        ),
        migrations.AddField(
            model_name='recording',
            name='converted_file_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Caminho do Arquivo Convertido'),
        ),
        migrations.AddField(
            model_name='recording',
            name='converted_file_size',
            field=models.BigIntegerField(default=0, verbose_name='Tamanho do Arquivo Convertido (bytes)'),
        ),
    ]
