# Generated by Django 4.2.7 on 2025-06-29 12:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Câmera')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('port', models.IntegerField(default=554, verbose_name='Porta')),
                ('stream_url', models.URLField(verbose_name='URL do Stream')),
                ('camera_type', models.CharField(choices=[('rtsp', 'RTSP'), ('http', 'HTTP'), ('onvif', 'ONVIF'), ('rtmp', 'RTMP')], default='rtsp', max_length=10, verbose_name='Tipo')),
                ('username', models.CharField(blank=True, max_length=50, verbose_name='Usuário')),
                ('password', models.CharField(blank=True, max_length=100, verbose_name='Senha')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Erro'), ('disconnected', 'Desconectado')], default='offline', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('motion_detection_enabled', models.BooleanField(default=True, verbose_name='Detecção de Movimento')),
                ('recording_enabled', models.BooleanField(default=True, verbose_name='Gravação Habilitada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Última Conexão')),
            ],
            options={
                'verbose_name': 'Câmera',
                'verbose_name_plural': 'Câmeras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CameraDiscovery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('port', models.IntegerField(default=80, verbose_name='Porta')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Fabricante')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Número de Série')),
                ('firmware_version', models.CharField(blank=True, max_length=50, verbose_name='Versão do Firmware')),
                ('onvif_url', models.URLField(blank=True, verbose_name='URL ONVIF')),
                ('rtsp_url', models.URLField(blank=True, verbose_name='URL RTSP')),
                ('status', models.CharField(choices=[('discovered', 'Descoberta'), ('added', 'Adicionada'), ('ignored', 'Ignorada')], default='discovered', max_length=20, verbose_name='Status')),
                ('discovered_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Descoberta')),
                ('added_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Adição')),
            ],
            options={
                'verbose_name': 'Câmera Descoberta',
                'verbose_name_plural': 'Câmeras Descobertas',
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='CameraSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motion_sensitivity', models.FloatField(default=0.3, verbose_name='Sensibilidade de Movimento')),
                ('recording_quality', models.CharField(default='medium', max_length=20, verbose_name='Qualidade da Gravação')),
                ('frame_rate', models.IntegerField(default=15, verbose_name='Taxa de Frames')),
                ('resolution_width', models.IntegerField(default=1920, verbose_name='Largura da Resolução')),
                ('resolution_height', models.IntegerField(default=1080, verbose_name='Altura da Resolução')),
                ('recording_duration', models.IntegerField(default=30, verbose_name='Duração da Gravação (segundos)')),
                ('motion_timeout', models.IntegerField(default=4, verbose_name='Timeout de Movimento (segundos)')),
                ('motion_start_delay', models.IntegerField(default=10, verbose_name='Delay de Início (segundos)')),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='cameras.camera')),
            ],
            options={
                'verbose_name': 'Configuração de Câmera',
                'verbose_name_plural': 'Configurações de Câmeras',
            },
        ),
    ]
