# Generated by Django 4.2.7 on 2025-06-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='stream_url',
            field=models.CharField(max_length=500, verbose_name='URL do Stream'),
        ),
    ]
